In [1]:
import pandas as pd

In [78]:
# https://minfin.gov.ru/ru/document?id_4=80042-kratkaya_ezhemesyachnaya_informatsiya_ob_ispolnenii_federalnogo_byudzheta_mlrd._rub._nakopleno_s_nachala_goda
data_input= pd.read_excel(r'D:\4. Programming\ProjectsSoftware\DA_study_projects\da_study\rf_budget\Prilozhenie_3_dannye_109-111_—_mes.xlsx')
data_input.head(5)

,Unnamed: 0,Приложение 3.3,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114,Unnamed: 115,Unnamed: 116,Unnamed: 117,Unnamed: 118,Unnamed: 119,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129,Unnamed: 130,Unnamed: 131,Unnamed: 132,Unnamed: 133,Unnamed: 134,Unnamed: 135,Unnamed: 136,Unnamed: 137,Unnamed: 138,Unnamed: 139,Unnamed: 140,Unnamed: 141,Unnamed: 142,Unnamed: 143,Unnamed: 144,Unnamed: 145,Unnamed: 146,Unnamed: 147,Unnamed: 148,Unnamed: 149,Unnamed: 150
0,NaN,Краткая информация об исполнении федерального ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,РАЗДЕЛ I,2011-01-01 00:00:00,2011-02-01 00:00:00,2011-03-01 00:00:00,2011-04-01 00:00:00,2011-05-01 00:00:00,2011-06-01 00:00:00,2011-07-01 00:00:00,2011-08-01 00:00:00,2011-09-01 00:00:00,2011-10-01 00:00:00,2011-11-01 00:00:00,2011-12-01 00:00:00,2012-01-01 00:00:00,2012-02-01 00:00:00,2012-03-01 00:00:00,2012-04-01 00:00:00,2012-05-01 00:00:00,2012-06-01 00:00:00,2012-07-01 00:00:00,2012-08-01 00:00:00,2012-09-01 00:00:00,2012-10-01 00:00:00,2012-11-01 00:00:00,2012-12-01 00:00:00,2013-01-01 00:00:00,2013-02-01 00:00:00,2013-03-01 00:00:00,2013-04-01 00:00:00,2013-05-01 00:00:00,2013-06-01 00:00:00,2013-07-01 00:00:00,2013-08-01 00:00:00,2013-09-01 00:00:00,2013-10-01 00:00:00,2013-11-01 00:00:00,2013-12-01 00:00:00,2014-01-01 00:00:00,2014-02-01 00:00:00,2014-03-01 00:00:00,2014-04-01 00:00:00,2014-05-01 00:00:00,2014-06-01 00:00:00,2014-07-01 00:00:00,2014-08-01 00:00:00,2014-09-01 00:00:00,2014-10-01 00:00:00,2014-11-01 00:00:00,2014-12-01 00:00:00,2015-01-01 00:00:00,2015-02-01 00:00:00,2015-03-01 00:00:00,2015-04-01 00:00:00,2015-05-01 00:00:00,2015-06-01 00:00:00,2015-07-01 00:00:00,2015-08-01 00:00:00,2015-09-01 00:00:00,2015-10-01 00:00:00,2015-11-01 00:00:00,2015-12-01 00:00:00,2016-01-01 00:00:00,2016-02-01 00:00:00,2016-03-01 00:00:00,2016-04-01 00:00:00,2016-05-01 00:00:00,2016-06-01 00:00:00,2016-07-01 00:00:00,2016-08-01 00:00:00,2016-09-01 00:00:00,2016-10-01 00:00:00,2016-11-01 00:00:00,2016-12-01 00:00:00,2017-01-01 00:00:00,2017-02-01 00:00:00,2017-03-01 00:00:00,2017-04-01 00:00:00,2017-05-01 00:00:00,2017-06-01 00:00:00,2017-07-01 00:00:00,2017-08-01 00:00:00,2017-09-01 00:00:00,2017-10-01 00:00:00,2017-11-01 00:00:00,2017-12-01 00:00:00,2018-01-01 00:00:00,2018-02-01 00:00:00,2018-03-01 00:00:00,2018-04-01 00:00:00,2018-05-01 00:00:00,2018-06-01 00:00:00,2018-07-01 00:00:00,2018-08-01 00:00:00,2018-09-01 00:00:00,2018-10-01 00:00:00,2018-11-01 00:00:00,2018-12-01 00:00:00,2019-01-01 00:00:00,2019-02-01 00:00:00,2019-03-01 00:00:00,2019-04-01 00:00:00,2019-05-01 00:00:00,2019-06-01 00:00:00,2019-07-01 00:00:00,2019-08-01 00:00:00,2019-09-01 00:00:00,2019-10-01 00:00:00,2019-11-01 00:00:00,2019-12-01 00:00:00,2020-01-01 00:00:00,2020-02-01 00:00:00,2020-03-01 00:00:00,2020-04-01 00:00:00,2020-05-01 00:00:00,2020-06-01 00:00:00,2020-07-01 00:00:00,2020-08-01 00:00:00,2020-09-01 00:00:00,2020-10-01 00:00:00,2020-11-01 00:00:00,2020-12-01 00:00:00,2021-01-01 00:00:00,2021-02-01 00:00:00,2021-03-01 00:00:00,2021-04-01 00:00:00,2021-05-01 00:00:00,2021-06-01 00:00:00,2021-07-01 00:00:00,2021-08-01 00:00:00,2021-09-01 00:00:00,2021-10-01 00:00:00,2021-11-01 00:00:00,2021-12-01 00:00:00,2022-01-01 00:00:00,2022-02-01 00:00:00,2022-03-01 00:00:00,2022-04-01 00:00:00,2022-05-01 00:00:00,2022-06-01 00:00:00,2022-07-01 00:00:00,2022-08-01 00:00:00,2022-09-01 00:00:00,2022-10-01 00:00:00,2022-11-01 00:00:00,2022-12-01 00:00:00,янв.23 ***,фев.23 ***,2023-03-01 00:00:00,2023-04-01 00:00:00,май.23 **
2,1,"Доходы, всего",804.858264,1505.608535,2392.782446,3339.693632,4200.038231,5306.370216,6233.830072,7220.201346,8213.020024,9240.763213,10164.760609,11367.652623,1059.559186,1865.966005,2966.312912,4058.679969,5083.326697,6200.39947,7245.938154,8352.074068,9385.360675,10453.22537,11404.844846,12855.540621,1093.098625,1981.299781,3105.607447,4224.408364,5115.5474,6257.653734,7330.012277,8418.161569,9604.469962,10740.597345,11758.713036,13019.939485,1326.688721,2368.552108,3521.419857,4754.274972,5882.573578,7120.906653,8255.667201,9439.624067,10698.307498,11891.596157,12951.397823,14496.880496,1324.184116,2278.941234,3438.079728,4550.104704,5360.768595,6620.872126,7796.044764,8959.927255,10145.3743,11337.254814,12176.12433,13659.242939,1094.047096,1841.939073,2910.684028,3910.109693,4645.70354,5868.748798,6970.311285,8143.979294,9295.427784,10441.593937,11436.828088,13460.040691,1265.992974,2290.888407,3633.280646,4763.721369,5830.547212,7122.0205,8371.167486,9607.91222,10971.469948,12283.600195,13418.735103,15088.914843,1304.47885,2534.74723,4076.325809,5528.995029,6914.865085,8626.7421,10496.158153,12222.398775,13986.148208,15802.349295,17454.914403,19454.369032,1486.33809,2843.971233,4590.01823,6361.144595,7867.426008,9549.863609,11471.32207,13256.739355,15034.722299,16671.168008,18025.630359,20188.796809,1556.549421,2818.890172,4731.33639,7001.993172,7891.040446,9091.870587,10399.705827,11688.330082,13216.68219,15145.395578,16528.605283,18719.089935,1503.985186,2755.563753,5299.923505,7486.826165,9320.269589,11265.770321,13651.128467,15697.751538,17923.871562,20431.745678,22440.033436,25286.377583,2088.812804,4205.523329,7163.122459,10033.791271,12042.740772,14017.117192,15774.36994,17606.554355,19739.237096,22139.466823,24779.831823,27824.392915,1357.005667,3164.240402,5678.939682,7785.107004,9818.030388
3,1.1.,Нефтегазовые доходы,355.598723,692.338578,1134.136196,1580.550506,2067.031151,2540.385273,3019.822999,3508.977952,3989.915585,4535.285702,5058.76706,5641.769451,530.215653,1015.766213,1544.855355,2104.810818,2688.081465,3226.109522,3734.466943,4224.973335,4739.65141,5276.18008,5842.467359,6453.184234,465.863552,976.71299,1503.668913,2087.616922,2611.325359,3099.109526,3635.732884,4180.566603,4774.166609,5359.608563,5940.734165,6534.035804,615.041101,1233.784015,1826.673254,2516.664782,3148.697728,3703.438582,4313.867722,4887.341658,5494.73394,6113.129578,6718.763009,7433.805828,520.777315,1046.335117,1545.55656,2018.479592,2471.378451,2976.017237,3505.124681,4033.176749,4511.573176,4971.069698,5411.040117,5862.65112,371.062082,687.726978,992.181118,1318.502233,1682.884406,2108.237321,2553.551066,2993.654728,3419.410319,3853.595926,4350.040799,4844.028538,485.13101,1014.901831,1517.865209,1974.173374,2440.003145,2888.56975,3304.5659,3753.928836,4246.2,4764.875677,5334.77244,5971.901701,661.344787,1289.557591,1859.652786,2490.32493,3174.869901,3935.044895,4684.26448,5501.805936,6302.082644,7222.058104,8181.641765,9017.774488,680.759261,1367.356828,1993.40035,2722.599739,3420.342605,4121.90146,4782.934582,5407.510489,6008.032905,6676.72394,7265.408393,7924.250828,615.942788,1224.268921,1787.931596,2222.492302,2436.727285,2661.046761,3002.071549,3406.950995,3854.013921,4328.524056,4782.26778,5235.245015,490.831996,1035.698245,1618,2511.412,3129.002593,3776,4770.024593,5465.856684,6184.768215,7292.692157,8177.377363,9056.506719,794.518794,1766.201572,2974.303738,4786.675528,5658.056399,6375.938904,7150.313156,7818.384965,8506.587413,9788.2564,10654.692399,11586.216011,425.515595,946.761727,1634.871752,2282.330923,2853.041982
4,1.2.,Ненефтегазовые доходы,449.259542,813.269957,1258.64625,1759.143126,2133.00708,2765.984943,3214.007073,3711.223394,4223.104439,4705.477511,5105.993549,5725.883172,529.343533,850.199792,1421.457557,1953.86915,2395.245232,2974.289948,3511.471211,4127.100733,4645.709264,5177.04529,5562.377487,6402.356388,627.235073,1004.586791,1601.938534,2136.791442,2504.222041,3158.544208,3694.279393,4237.594967,4830.303353,5380.988782,5817.978871,6485.903681,711.64762,1134.768093,1694.746603,2237.61019,2733.87585,3417.468071,3941.799479,4552.282409,5203.573558,5778.466579,6232.634814,7063.074668,803.406801,1232.606117,1892.523168,2531.625112,2889.390145,3644.854889,4290.920083,4926.750506,5633.801123,6366.185116,6765.084214,7796.591819,722.985015,1154.212095,1918.50291,2591.607461,2962.819134,3760.511477,4416.760219,5150.324567,5876.017465,6587.998011,7086.787289,8616.012153,780.861963,1275.986576,2115.415437,2789.547994,3390.544068,4233.450751,5066.601586,5853.983384,6725.269948,7518.724517,8083.962662,9117.013142,643.134063,1245.189638,2216.673023,3038.670099,3739.995184,4691.697205,5811.893673,6720.592839,7684.065564,8580.291191,9273.272637,10436.594544,805.578829,1476.614405,2596.61788,3638.544855,4447.083402,5427.962149,6688.387488,7849.228866,9026.689394,9994.444069,10760.221966,12264.54598,940.606632,1594.621251,2943.404794,4779.50087,5454.313162,6430.823825,7397.634278,8281.379087,9362.668269,10816.871523,11746.337503,13483.84492,1013.15319,1719.865509,3681.923505,4975.414165,6191.266996,7489.770321,8881.103874,10231.894854,11739.103347,13139.05352,14262.656074,16229.870864,1294.294011,2439.321757,4188.818722,5247.115743,6384.684374,7641.178288,8624.056784,9788.169389,11232.649683,12351.210423,14125.139424,16238.176903,931.490072,2217.478675,4044.06793,5502.776081,6964.988406

In [79]:
data_input = data_input.T
data_input = data_input.reset_index(drop=True)
first_ = data_input.drop(axis=1,columns=[0])


# data_input = data_input.drop(axis=0,index=0)
# data_input.columns = data_input.iloc['РАЗДЕЛ I']
# first_
# data_input.drop(axis=1,columns=['Unnamed: 0'])
# data_input.head()

In [56]:
categories = first_.loc[0:1,:]
categories

,1,2,3,4,5,6,7,8,9,10,...,44,45,46,47,48,49,50,51,52,53
0,NaN,1,1.1.,1.2.,1.2.1.,1.2.1.1.,1.2.1.2.,1.2.1.3.,1.2.1.4.,1.2.2.,...,4.1.4.,4.1.5.,4.1.6.,4.1.7.,4.2.,4.2.1.,4.2.2.,4.2.3.,NaN,* Государственные (муниципальные) ценные бумаг...
1,РАЗДЕЛ I,"Доходы, всего",Нефтегазовые доходы,Ненефтегазовые доходы,Связанные с внутренним производством,НДС (внутренний),Акцизы,Налог на прибыль,Налог на доходы физических лиц,Связанные с импортом,...,Поступления от продажи акций и земельных участ...,Курсовая разница,Изменение остатков на счетах,Прочее,Источники внешнего финансирования дефицита,Привлечение кредитов и размещение ценных бумаг,Погашение внешнего долга,Другие источники внешнего финансирования,NaN,NaN

In [80]:
some_df = first_.loc[0,:]

In [81]:
first_.columns = some_df
first_ = first_.iloc[:, :-1].drop(axis=0,index=[0,1]).rename(columns={first_.columns[0]:'date'})

In [93]:
# first_.date = first_.date.apply(pd.to_datetime)
# 
budg = 86_262_000_000
mean_pens= 19_435
periods =12
people= 41_775_000
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
first_.loc[[146,147,150],:]

0          date            1         1.1.         1.2.       1.2.1.     1.2.1.1.    1.2.1.2.    1.2.1.3.   1.2.1.4.       1.2.2.      1.2.2.1   1.2.2.2.    1.2.2.3.      1.2.3. date             2 2.1. 2.2. 2.3. 2.4. 2.5. 2.6. 2.7. 2.8. 2.9. 2.10. 2.11. 2.12. 2.13. 2.14. date            3         3.1. date            4         4.1.       4.1.1.      4.1.2.    4.1.2.1.    4.1.2.2. 4.1.3. 4.1.3.1. 4.1.3.2.    4.1.4.      4.1.5.       4.1.6.       4.1.7.      4.2. 4.2.1. 4.2.2.    4.2.3. date
146  янв.23 ***  1357.005667   425.515595   931.490072    443.04867   379.471533  133.665896   -71.87036   1.781601    352.21706   282.296256  10.667928   59.252876  136.224343  NaN   3006.330687  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN   NaN   NaN   NaN   NaN  NaN  -1649.32502 -2074.840615  NaN   1649.32502  1655.842821  3094.076605   -8.088063  173.345063 -181.433125      0        0        0  0.162143  239.517373 -1438.233784  2862.485152 -5.652512      0      0 -5.652512  NaN
147  фев.23 ***  3164.240402   946.761727  2217.478675  1290.115291  1059.681709  197.505344   22.496548   10.43169   703.113218   561.940984  20.585058  120.587176  224.250167  NaN   5543.147105  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN   NaN   NaN   NaN   NaN  NaN -2378.906703 -3325.668429  NaN  2378.906703   4065.85825  4203.237762  267.615168  449.207927 -181.592759      0        0        0  0.168243  486.404036  -137.379512  3449.050315 -24.48373      0      0 -24.48373  NaN
150   май.23 **  9818.030388  2853.041982  6964.988406  3941.256589  2741.430119   474.96797  688.322766  36.535735  2063.097029  1626.460828   57.22204  379.414161  960.634788  NaN  13228.995229  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN   NaN   NaN   NaN   NaN  NaN  -3410.96484 -6264.006823  NaN          NaN          NaN          NaN         NaN         NaN         NaN    NaN      NaN      NaN       NaN         NaN          NaN          NaN       NaN    NaN    NaN       NaN  NaN

In [ ]:
import re
len(data.columns)

# data.drop(axis=1,columns='РАЗДЕЛ I').shape
data_input = data.T
# data_raw['year'] = data_raw.index.str
# data_raw.index.apply(lambda x: re.search('\d\d',x.str)[0],x)
data_input['header_col']  = data_raw.index
data_raw
# data_raw['year']    =data_raw['header_col'].apply(lambda x: re.match('\d\d',x)[0])
# data_raw.year